### ISSUE TITLE
Highlight the key being authenticated

### ISSUE THREAD

**Issue by dongjing-github** [google/webauthndemo#21]
Copy/paste the issue filed by QA.

1. Have a fingerprint and screen lock credential set up
2. Open Chromium
3. Visit a FIDO2 enabled website on Chromium and Provide any account that works
4. Click “REGISTER NEW CREDENTIAL”
5. Complete the flow of Registration with instructions on Screen for fingerprint
6. Complete another registration for screen lock
7. Now try to authenticate using either fingerprint or screen lock.

Expected: Successful assertion message plus will display in red or pink which key has been asserted like in the app

Actual: It does not really specify which one.

**Comment by cpiper** [comment]
https://github.com/google/webauthndemo/commit/5cd52e55c60d20ccd30dac0b40bfefdd6cf8715c
