### ISSUE TITLE
UI enhancement - grey out page when webauthn dialog is showing

### ISSUE THREAD

**Issue by kpaulh** [google/webauthndemo#56]
Just a 'nice to have' feature :-)

**Comment by DamianArado** [comment]
Hii @kpaulh, can you please elaborate more on the requirements of the feature. 😸

**Comment by kpaulh** [comment]
Hi, I'm under the impression that webauthndemo is no longer supported, so I'll go ahead and close this.
(But as best I can remember from when I opened this issue, it was just to have the webpage grey out or otherwise signal that it is inactive when the webauthn modal UI pops up. It would look nicer and indicate to people that they cannot interact with it until the webauthn dialog is dismissed.)
