### ISSUE TITLE
Bug: register with fingerprint

### ISSUE THREAD

**Issue by IIcuxoIIaTiK** [google/webauthndemo#65]
In your demo https://webauthndemo.appspot.com/ when you try to register a new account with smartphone using a fingerprint, an error occurs  

`An error occurred during Make Credential operation [NotReadableError: An unknown error occurred while talking to the credential manager.]
`
os - android 9
smartphone - galaxy s9+
browser - chrome(v 72.0.3626.121) and chrome beta(v 73.0.3683.75)

**Comment by cpiper** [comment]
That error is returned by the client, the demo is just showing the error to you (it's not an error on the server side). FWIW, I am unable to reproduce the error. Do you have a screenlock set up on the device?

**Comment by IIcuxoIIaTiK** [comment]
If you are asking about whether a fingerprint is added to unlock the phone, then yes, it’s added.

**Comment by cpiper** [comment]
Ok, then this is an issue on the client side. I would suggest filing a bug with Chrome, as there is nothing that can be done on the server side.

**Comment by mahnunchik** [comment]
@cpiper could you share any information you have about the issue.

**Comment by thealidev** [comment]
I am facing this issue too on internet computer protocol website !!
It's for years already on this issue created
Is it still not fixed ??

**Comment by agektmr** [comment]
@thealidev We've rewrote the site with JS from scratch. Your issue must be different than what's described here. Could you file another issue with details of your environment?
