### ISSUE TITLE
Add UVM extension option

### ISSUE THREAD

**Issue by kpaulh** [google/webauthndemo#68]
Allow passing of the UVM extension input and display the output.

**Comment by DeenOub** [comment]
I see the option is now here, but does it work ? I can't see any differences whether it is checked or not.  I am using Chrome 75 and a Yubikey 5 NFC.

**Comment by suzylii** [comment]
UVM extension is available on Android platform and will land on Chrome 77. Please try it on Chrome canary, and make sure your Google Play Service version (which can be seen from the apps menu in settings -> apps -> Google Play Service) is above 16200000.
