### ISSUE TITLE
caBLE support

### ISSUE THREAD

**Issue by ynojima** [google/webauthndemo#70]
I heard caBLE is supported by Chrome. If this demo supports caBLE, it would be helpful for relying parties who would like to support caBLE.

**Comment by cpiper** [comment]
We're looking at adding support for caBLE to the demo, but currently don't have a timeline for this.

**Comment by cpiper** [comment]
This is now implemented in https://github.com/google/webauthndemo/commit/8c588e670f31807b6bd069b8cf71798baa9a673b

**Comment by ynojima** [comment]
I tried the demo, but don't like the "google.com", my Pixel 3 didn't wake up when the "REGISTER NEW CREDENTIAL" button was clicked on my labtop with BLE.
Is there any prerequisites for caBLE registration?

**Comment by cpiper** [comment]
Just to clarify, this is supported on the demo website, but not on Android at this point.

**Comment by ynojima** [comment]
Thank you for clarification.
