### ISSUE TITLE
Android phone's built-in security key for Linux

### ISSUE THREAD

**Issue by WhiteTrashLord** [google/webauthndemo#76]
I would like to test your demo on my laptop. But I don't have a physical security key. I would like to use my Android phone as a security key. But I am using Linux. On this site I read that you currently don't support Linux :(

https://support.google.com/accounts/answer/9289445?co=GENIE.Platform%3DDesktop&hl=en

Will you add support for Linux soon?

**Comment by cpiper** [comment]
Hi, to clarify, Google's implementation of using phones as a security key is custom and will not work on this demo website. The demo does have support for generating "cable" credentials but Android does not yet have support for handling them.

If you wanted to test without a physical security key you can test directly on your phone with the built in screenlock or with a testing software version of a security key.
