### ISSUE TITLE
The ISUVPAA button reports wrong in Android Firefox

### ISSUE THREAD

**Issue by koresar** [google/webauthndemo#77]
* Install Firefox browser for Android
* Open the page and click "ISUVPAA" (maybe rename the button? I have no idea what that means.)
Problem: the toast message says "... NOT available".
Actual: When clicking "REGISTER PLATFORM ..." the Firefox does work as expected (like Chrome does). So, yeah, it is available.

Suggestion:
Implement the ISUVPAA button using only client-side JavaScript.

**Comment by cpiper** [comment]
The isUVPAA button calls the API:
https://www.w3.org/TR/webauthn/#isUserVerifyingPlatformAuthenticatorAvailable
and is implemented in client side JS here:
https://github.com/google/webauthndemo/blob/67ff392f18f8244800d9d5184219bef3c0615437/src/main/webapp/js/webauthn.js#L414

Firefox as a browser needs to expose the API, so this is probably an issue on the browser side.

**Comment by koresar** [comment]
Found it! Thank you

For all the others:
https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable
